config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"

  resources :users
  get "signup" => "users#new"
  root "movies#index"
  resources :movies do
    resources :reviews
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :reviews, dependent: :destroy
    validates :title, :released_on, :duration, presence: true
    validates :description, length: { minimum: 25 }
    validates :total_gross, numericality: { greater_than_or_equal_to: 0 }
    validates :image_file_name, format: {
                with: /\w+\.(jpg|png)\z/i,
                message: "must be a JPG or PNG image"
                }
    RATINGS = %w(G PG PG-13 R NC-17)
    validates :rating, inclusion: { in: RATINGS }  
              
    def flop?
        total_gross.blank? || total_gross < 225000000
    end

    def self.released
        Movie.where("released_on < ?", Time.now).order("released_on desc")
    end

    def average_stars
        reviews.average(:stars) || 0.0
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie

  validates :name, presence: true
  validates :comment, length: { minimum: 4 }
  STARS= [ 1, 2, 3, 4, 5 ]
  validates :stars, inclusion: {in: STARS, message: "must be between 1 and 5"}

  def stars_as_percent
    (stars / 5.0) * 100.0
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name,:email, presence: true
  validates :email,format: { with: /\S+@\S+/ },
            uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6, allow_blank: true }
  validates :username, format: { with: /\A[A-Z0-9]+\z/i },
                     uniqueness: { case_sensitive: false }

  def gravatar_id
    Digest::MD5::hexdigest(email.downcase)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types(:danger)
    
    private

    def require_signin
        unless current_user
            session[:intended_url] = request.url
            redirect_to new_session_url, alert: "Please sign in first!"
        end
    end

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      end
    
    helper_method :current_user

    def current_user?(user)
        current_user == user
    end
    
    helper_method :current_user?

    def current_user_admin?
        current_user && current_user.admin?
    end
    
    helper_method :current_user_admin?
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :require_signin, except: [:index, :show]
    before_action :require_admin, except: [:index, :show]
    def index
        @movies = Movie.released
    end

    def show
        @movie = Movie.find(params[:id])
    end

    def edit
        @movie = Movie.find(params[:id])
    end
    
    def update
        @movie = Movie.find(params[:id])

        if @movie.update(movie_params)
            redirect_to @movie, notice: "Movie successfully updated!"
        else
            render :edit
        end
    end

    def new
        @movie = Movie.new
    end

    def create
        @movie = Movie.new(movie_params)
        if @movie.save
            redirect_to @movie, notice: "Movie successfully created!"
        else
            render :new
        end
    end

    def destroy
        @movie = Movie.find(params[:id])
        @movie.destroy
        redirect_to movies_url, alert: "Movie successfully deleted!"
    end

    private

    def movie_params
        params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross, :director, :duration, :image_file_name)
    end

    def require_admin
        unless current_user_admin?
          redirect_to root_url, alert: "Unauthorized access!"
        end
    end
      
    def current_user_admin?
        current_user && current_user.admin?
    end
    
    helper_method :current_user_admin?
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_movie

    def index
        @reviews = @movie.reviews 
    end
    def new
        @review = @movie.reviews.new
    end

    def create
        @review = @movie.reviews.new(review_params)
      
        if @review.save
          redirect_to movie_reviews_path(@movie),
                        notice: "Thanks for your review!"
        else
          render :new
        end
    end

    def set_movie
        @movie = Movie.find(params[:movie_id])
    end
      
      private
      
      def review_params
        params.require(:review).permit(:name, :comment, :stars)
      end

      
      
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
        user = User.find_by(email: params[:email_or_username]) || User.find_by(username: params[:email_or_username])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to (session[:intended_url] || user),
                   notice: "Welcome back, #{user.name}!"
            session[:intended_url] = nil
        else
            flash.now[:alert]="Invalid Email/Password Combination"
            render :new 
        end
    end
  
    def destroy
        session[:user_id] = nil
        redirect_to movies_url, notice: "You are now signed out!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_signin, except: [:new,:create]
    before_action :require_currect_user, only: [:edit, :update]
    before_action :require_admin, only: [:destroy]
    def index
        @users = User.all
    end

    def show
        @user = User.find(session[:user_id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to @user, notice: "Thanks for signing up!"
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
          redirect_to @user, notice: "Account successfully updated!"
        else
          render :edit
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to root_url, alert: "Account successfully deleted!"
    end
      
    private

    def user_params
    params.require(:user).
        permit(:name, :email, :password, :password_confirmation, :username)
    end

    def require_currect_user
        @user = User.find(params[:id])
        redirect_to root_url unless current_user?(@user)
    end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
    def total_gross(movie)
        if movie.flop?
            "Flop!"
        else 
            number_to_currency(movie.total_gross, precision: 0)
        end 
    end

    def year_of(movie)
        movie.released_on.year
    end

    def average_stars(movie)
        if movie.average_stars.zero?
            content_tag(:strong, "No reviews")
        else
            pluralize(number_with_precision(movie.average_stars, precision: 1) , "star")
        end
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def profile_image(user)
        url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
        image_tag(url, alt: user.name)
    end
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
      <p>
        Copyright &copy; 2020-<%= Time.now.year %>
        <%= link_to 'The Movie Studio','https://localhost:3000/movies' %>
      </p>
    </footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= image_tag("logo") %>
    <ul class="left">
      <li>
        <%= link_to "All Movies", "/movies"%>
      </li>
    </ul>
    <ul class="right">
      <% if current_user %>
       <li>
        <%= link_to current_user.name, current_user %>
      </li>
      <li>
        <%= link_to "Account Settings", edit_user_path(current_user) %>
      </li>
      <li>
        <%= link_to "Sign Out", session_path, method: :delete, class: "button" %>
      </li>
      <% else %>
      <li>
        <%= link_to "Sign In", signin_path, class: "button" %>
        <%= link_to "Sign Up", signup_path, class: "button" %>
      </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super-Heroic Flix</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="content">
      <%= render "layouts/flash"%>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: @movie, local: true) do |f| %>
    <%= movie.errors.full_messages.to_sentence %>
    <%= render "shared/errors", object: movie %>

    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true %>

    <%= f.label :description %>
    <%= f.text_field :description, rows: 10 %>

    <%= f.label :rating %>
    <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>

    <%= f.label :released_on %>
    <%= f.date_field :released_on %>

    <%= f.label :total_gross %>
    <%= f.number_field :total_gross %>

    <%= f.label :director %>
    <%= f.text_field :director %>

    <%= f.label :duration %>
    <%= f.text_field :duration %>

    <%= f.label :image_file_name %>
    <%= f.text_field :image_file_name %>

    <%= f.submit %>
<% end %>

app/views/movies/edit.html.erb
<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
  <section class="movie">
    <div class="image">
      <%= image_tag movie.image_file_name %>
    </div>
    <div class="summary">
      <h2>
        <%= link_to movie.title, movie %>
      </h2>
      <h3>
        <%= total_gross(movie) %>
      </h3>
      <span class="stars">
        <%= average_stars(movie) %>
      </span>
      <p>
        <%= truncate(movie.description, length: 150, separator: ' ') %>
      </p>
    </div>
  </section>
<% end %>
<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Add New Movie", new_movie_path, class: "button" %>
  </section>
<% end %>

app/views/movies/new.html.erb
<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<section class="movie-details">
  <div class="image">
    <%= image_tag @movie.image_file_name %>
  </div>
  <div class="details">
    <h1><%= @movie.title %></h1>
    <h2>
      <%= year_of(@movie) %> &bull; <%= @movie.rating %>
    </h2>
    <div class="reviews">
      <%= average_stars(@movie) %>
      <%= link_to pluralize(@movie.reviews.size, "Review"), movie_reviews_path(@movie) %>
    </div>
    <p>
      <%= @movie.description %>
    </p>
    <table>
      <tr>
          <th>Director:</th>
          <td><%= @movie.director %></td>
        </tr>
        <tr>
          <th>Duration:</th>
          <td><%= @movie.duration %></td>
        </tr>
      <tr>
        <th>Total Gross:</th>
        <td><%= total_gross(@movie) %></td>
      </tr>
    </table>
    <%= link_to "Write Review", new_movie_review_path(@movie),
              class: "review" %>
  </div>
</section>
<% if current_user_admin? %>
<section class="admin">
  <%= link_to "Edit", edit_movie_path(@movie), class: "button" %>
  <%= link_to 'Delete', movie_path(@movie), class: 'button', method: :delete, data: { confirm: 'Are you sure?' } %>
</section>
<% end %>

app/views/reviews/index.html.erb
<ul class="reviews">
  <% @reviews.each do |review| %>
    <li>
      <%= render "shared/stars", percent: review.stars_as_percent %>
      <p>
        <%= review.name %>
        <span class="date">
          <%= time_ago_in_words(review.created_at) %> ago
        </span>
      </p>
      <p>
        <%= review.comment %>
      </p>
    </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<h1>New Review for <%= link_to @movie.title, @movie %></h1>
<%= form_with(model: [@movie, @review], local: true) do |f| %>
  <%= render "shared/errors", object: @review %>
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :stars %>
    <% Review::STARS.each do |star| %>
        <span class="star">
            <%= f.radio_button :stars, star %>
            <%= label_tag star %>
        </span>
    <% end %>

  <%= f.label :comment %>
  <%= f.text_area :comment, placeholder: "What did you think?" %>

  <%= f.submit "Post Review" %>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/shared/_stars.html.erb
<div class="star-rating">
  <div class="back-stars">
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <div class="front-stars" style="width: <%= percent %>%">
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= render "shared/errors", object: user %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :username %>
  <%= f.text_field :username, placeholder: "Alphanumeric characters only!" %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

  <% if user.new_record? %>
    <%= f.submit "Create Account" %>
  <% else %>
    <%= f.submit "Update Account" %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>
<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, "User") %></h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      created
      <%= time_ago_in_words(user.created_at) %> ago
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "form", user: @user %>

app/views/users/show.html.erb
<section class="user">
    <%= profile_image(@user) %>
    <h1><%= @user.name %></h1>
    <h2><%= mail_to(@user.email) %></h2>
    <h3>Member Since</h3>
    <p>
        <%= @user.created_at.strftime("%B %Y") %>
     </p>
     
     <div class="actions">
        <% if current_user?(@user) %>
        <%= link_to "Edit Account", edit_user_path(@user),
                    class: "button edit" %>
        <% end %>
        <% if current_user_admin? %>
        <%= link_to 'Delete Account', @user, method: :delete,
              data: { confirm: "Permanently delete your account!?" },
              class: "button delete" %>
        <% end %>
    </div>
    
</section>